const $=s=>document.querySelector(s), app=$("#app");
const clamp=(n,min,max)=>Math.min(max,Math.max(min,n));
const emptyState=()=>({answers:{},wrong:[],history:[],drafts:{}});
let rawState;
try{rawState=JSON.parse(localStorage.getItem("osuiStateV5")||localStorage.getItem("osuiStateV4")||"null")}catch(e){rawState=null}
let state=Object.assign(emptyState(),rawState||{});
state.answers=state.answers||{};state.wrong=Array.isArray(state.wrong)?state.wrong:[];state.history=Array.isArray(state.history)?state.history:[];state.drafts=state.drafts||{};
let current=[],pos=0,mode="year",active=null;
let zoomState={scale:1,x:0,y:0,dragging:false,lastX:0,lastY:0,pinchStart:0,pinchBase:1};
function save(){localStorage.setItem("osuiStateV5",JSON.stringify(state))}
function answered(){return Object.keys(state.answers).filter(id=>QUESTIONS.some(q=>q.id===id)).length}
function correct(){return Object.entries(state.answers).filter(([id,v])=>v===true&&QUESTIONS.some(q=>q.id===id)).length}
function setTab(t){document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.tab===t));({home,years,review,stats}[t]||home)()}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>setTab(b.dataset.tab));
function currentQuestion(){return current[pos]}
function draftKey(y){return `year:${y}`}
function draftInfo(y){let d=state.drafts[draftKey(y)];if(!d||!d.answers)return null;return d}
function draftCount(y){let d=draftInfo(y);return d?Object.keys(d.answers).length:0}
function home(){let a=answered(),total=QUESTIONS.length,pct=Math.round(a/total*100),drafts=YEARS.filter(y=>draftCount(y)>0).length;app.innerHTML=`<section class="hero"><span class="badge">10年分 v15・回答履歴修正版</span><h2>汚水処理特論 250問</h2><p>平成27年度〜令和6年度の250問を収録。新しく解き始めると選択肢は未選択から始まり、途中保存と過去の成績は別々に保持されます。</p><div class="progress"><i style="width:${pct}%"></i></div><small>全体進捗 ${a}/${total}問（${pct}%）${drafts?`・途中保存 ${drafts}年度`:''}</small></section><div class="metric-row"><div class="metric"><b>${a}</b><span>回答経験</span></div><div class="metric"><b>${correct()}</b><span>最新回答で正解</span></div><div class="metric"><b>${a?Math.round(correct()/a*100):0}%</b><span>最新正答率</span></div></div><h3 class="section-title">今日の学習</h3><div class="actions"><button class="action" onclick="randomQuiz()">ランダム10問<small>毎回未選択から開始</small></button><button class="action alt" onclick="review()">間違い直し<small>${state.wrong.length}問</small></button></div><h3 class="section-title">年度別</h3><div class="card row"><div><b>10年度すべて開放</b><br><small>「最初から」「続きから」を選択できます</small></div><button class="primary compact" onclick="years()">選ぶ</button></div><p class="notice">※過去に解いた問題でも、新しい演習では正答や選択状態を表示しません。途中から再開した場合だけ、その演習中の回答を復元します。</p>`}
function years(){app.innerHTML=`<h2>年度別演習</h2><p class="sub">年度を選ぶと「最初から解く／続きから解く」を選べます。過去の成績は消えません。</p><div class="years">${YEARS.map((y,i)=>{let qs=QUESTIONS.filter(q=>q.year===y),n=qs.filter(q=>q.id in state.answers).length,d=draftCount(y);return `<button class="year" onclick="startYear(${i})"><b>${y}</b><span>${n}/25問 回答経験${d?`・途中 ${d}問`:''}</span><div class="mini"><i style="width:${n*4}%"></i></div></button>`}).join("")}</div>`}
function startYear(i){let y=YEARS[i],d=draftInfo(y),dcount=draftCount(y),latest=state.history.find(h=>h.kind==='year'&&h.year===y);app.innerHTML=`<h2>${y}</h2><div class="card"><b>演習方法を選択</b><p class="sub">「最初から解く」では、過去に解いた選択肢や正解表示を引き継ぎません。成績履歴はそのまま残ります。</p>${latest?`<p class="sub">直近の完了成績：${latest.score}/${latest.total}問</p>`:''}<div class="start-actions"><button class="primary" onclick="beginYear(${i},false)">最初から解く</button><button class="secondary" ${dcount?`onclick="beginYear(${i},true)"`:'disabled'}>続きから解く${dcount?`（${dcount}問回答済み）`:'（途中保存なし）'}</button></div></div><button class="secondary full" onclick="years()">年度一覧へ戻る</button>`}
function beginYear(i,resume){let y=YEARS[i],key=draftKey(y),old=draftInfo(y);if(!resume){if(old&&Object.keys(old.answers||{}).length&& !confirm('この年度の途中回答を破棄して、未選択の状態から始めますか？\n過去の成績履歴は残ります。'))return;state.drafts[key]={answers:{},pos:0,updated:Date.now()};save()}let d=state.drafts[key]||{answers:{},pos:0};mode="year";current=QUESTIONS.filter(q=>q.year===y);pos=clamp(Number(d.pos)||0,0,current.length-1);active={kind:"year",year:y,key,persist:true,answers:d.answers||{}};showQ()}
function randomQuiz(){mode="random";current=[...QUESTIONS].sort(()=>Math.random()-.5).slice(0,10);pos=0;active={kind:"random",year:null,key:null,persist:false,answers:{}};showQ()}
function review(){let ids=[...new Set(state.wrong)];current=ids.map(id=>QUESTIONS.find(q=>q.id===id)).filter(Boolean);mode="review";pos=0;active={kind:"review",year:null,key:null,persist:false,answers:{}};if(!current.length){app.innerHTML='<div class="empty"><h2>復習問題はまだないよ</h2><p>間違えた問題が自動でここに入ります。</p></div>';return}showQ()}
function assetCard(title,html,kind,note=''){return `<div class="asset-card"><div class="asset-head"><b>${title}</b><button class="zoom-btn" type="button" onclick="openZoom('${kind}')">拡大</button></div>${html}${note?`<p class="asset-note">${note}</p>`:''}</div>`}
function visualHTML(q){const parts=[];if(q.visual)parts.push(assetCard('図',q.visual,'visual','通常表示は画面幅に自動フィット。拡大ではピンチ操作ができます。'));if(q.formula)parts.push(assetCard('式・条件',`<div class="formula">${q.formula.replace(/\n/g,'<br>')}</div>`,'formula','横スクロールなしで表示します。'));return parts.join('')}
function saveActive(){if(active&&active.persist){state.drafts[active.key]={answers:active.answers,pos,updated:Date.now()};save()}}
function showQ(){let q=current[pos];if(!q){home();return}let old=active&&active.answers?active.answers[q.id]:undefined;app.innerHTML=`<div class="qtop"><span>${q.year}・問${q.number}</span><span>${pos+1}/${current.length}</span></div><div class="progress"><i style="width:${(pos+1)/current.length*100}%"></i></div><section class="qcard"><span class="badge">${q.topic}</span><h2>${q.text}</h2>${visualHTML(q)}<div class="choices">${q.choices.map((c,i)=>`<button class="choice" data-i="${i}" onclick="pick(${i})"><b>${i+1}.</b> ${c}</button>`).join("")}</div><div id="result"></div></section><div class="pager"><button class="secondary" onclick="prev()">前へ</button><button class="primary" onclick="next()">次へ</button></div>`;if(old!==undefined)reveal(q,old.ok,old.chosen)}
function pick(i){let q=current[pos],ok=q.corrects.includes(i);active.answers[q.id]={ok,chosen:i};state.answers[q.id]=ok;if(ok)state.wrong=state.wrong.filter(x=>x!==q.id);else if(!state.wrong.includes(q.id))state.wrong.push(q.id);saveActive();if(!active.persist)save();reveal(q,ok,i)}
function reveal(q,ok,chosen){document.querySelectorAll('.choice').forEach((b,i)=>{b.disabled=true;if(q.corrects.includes(i))b.classList.add('correct');if(chosen===i&&!ok)b.classList.add('wrong')});let ans=q.corrects.map(i=>i+1).join('・');$('#result').innerHTML=`<div class="explain"><b class="${ok?'ok':'bad'}">${ok?'正解！':'不正解'}　答え ${ans}</b><div class="official">公式正答番号：${q.officialAnswer}</div>${q.explain}</div>`}
function next(){if(pos<current.length-1){pos++;saveActive();showQ()}else finish()}
function prev(){if(pos>0){pos--;saveActive();showQ()}}
function finish(){let entries=Object.values(active?.answers||{}),n=entries.filter(x=>x.ok===true).length,done=entries.length,total=current.length;let rec={kind:active?.kind||mode,year:active?.year||null,score:n,total,answered:done,ts:Date.now()};state.history.unshift(rec);state.history=state.history.slice(0,50);if(active?.persist)delete state.drafts[active.key];save();app.innerHTML=`<section class="hero"><h2>演習終了</h2><p>今回のセットの記録</p><div class="score">${n}/${total}</div><p class="sub">回答 ${done}/${total}問。この成績は履歴に保存しました。</p><button class="primary" onclick="home()">ホームへ</button></section>`}
function historyLabel(h){if(h.kind==='year')return h.year||'年度別';if(h.kind==='random')return 'ランダム10問';return '間違い直し'}
function stats(){let a=answered(),c=correct();let hist=state.history.slice(0,12).map(h=>`<div class="card row yearstat"><div><b>${historyLabel(h)}</b><br><small>${new Date(h.ts).toLocaleString('ja-JP')}</small></div><span>${h.score}/${h.total}問</span></div>`).join('');app.innerHTML=`<h2>学習成績</h2><div class="metric-row"><div class="metric"><b>${a}</b><span>回答経験</span></div><div class="metric"><b>${c}</b><span>最新回答で正解</span></div><div class="metric"><b>${a?Math.round(c/a*100):0}%</b><span>最新正答率</span></div></div><h3 class="section-title">年度別（最新回答）</h3>${YEARS.map(y=>{let q=QUESTIONS.filter(x=>x.year===y),done=q.filter(x=>x.id in state.answers).length,ok=q.filter(x=>state.answers[x.id]===true).length;return `<div class="card row yearstat"><b>${y}</b><span>${ok}正解 / ${done}回答</span></div>`}).join('')}<h3 class="section-title">完了した演習履歴</h3>${hist||'<p class="sub">v15以降に完了した演習がここに残ります。以前の回答実績は上の年度別成績として引き継いでいます。</p>'}<button class="secondary danger full" onclick="resetAll()">学習記録をリセット</button>`}
function resetAll(){if(confirm('回答履歴・途中保存・成績履歴をすべて消しますか？')){state=emptyState();localStorage.removeItem('osuiStateV4');save();stats()}}
function ensureZoomModal(){if($('#zoomModal'))return;document.body.insertAdjacentHTML('beforeend',`<div id="zoomModal" class="zoom-modal" aria-hidden="true"><div class="zoom-shell"><div class="zoom-top"><div class="zoom-title" id="zoomModalTitle">拡大表示</div><div class="zoom-tools"><button type="button" class="tool-btn" onclick="zoomOut()">−</button><button type="button" class="tool-btn" onclick="zoomReset()">100%</button><button type="button" class="tool-btn" onclick="zoomIn()">＋</button><button type="button" class="tool-btn close" onclick="closeZoom()">閉じる</button></div></div><div id="zoomHint" class="zoom-hint">ピンチで拡大縮小・1本指で移動できます</div><div id="zoomViewport" class="zoom-viewport"><div id="zoomPane" class="zoom-pane"></div></div></div></div>`);const modal=$('#zoomModal'),viewport=$('#zoomViewport');modal.addEventListener('click',e=>{if(e.target===modal)closeZoom()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.classList.contains('show'))closeZoom()});viewport.addEventListener('wheel',e=>{if(!modal.classList.contains('show'))return;e.preventDefault();zoomState.scale=clamp(zoomState.scale+(e.deltaY<0?.18:-.18),1,5);applyZoom()},{passive:false});viewport.addEventListener('mousedown',e=>{if(zoomState.scale<=1)return;zoomState.dragging=true;zoomState.lastX=e.clientX;zoomState.lastY=e.clientY});window.addEventListener('mousemove',e=>{if(!zoomState.dragging)return;zoomState.x+=e.clientX-zoomState.lastX;zoomState.y+=e.clientY-zoomState.lastY;zoomState.lastX=e.clientX;zoomState.lastY=e.clientY;applyZoom()});window.addEventListener('mouseup',()=>zoomState.dragging=false);viewport.addEventListener('touchstart',e=>{if(e.touches.length===2){zoomState.pinchStart=touchDistance(e.touches[0],e.touches[1]);zoomState.pinchBase=zoomState.scale}else if(e.touches.length===1&&zoomState.scale>1){zoomState.dragging=true;zoomState.lastX=e.touches[0].clientX;zoomState.lastY=e.touches[0].clientY}},{passive:true});viewport.addEventListener('touchmove',e=>{if(e.touches.length===2){let d=touchDistance(e.touches[0],e.touches[1]);if(zoomState.pinchStart){zoomState.scale=clamp(zoomState.pinchBase*(d/zoomState.pinchStart),1,5);applyZoom()}}else if(e.touches.length===1&&zoomState.dragging&&zoomState.scale>1){let t=e.touches[0];zoomState.x+=t.clientX-zoomState.lastX;zoomState.y+=t.clientY-zoomState.lastY;zoomState.lastX=t.clientX;zoomState.lastY=t.clientY;applyZoom()}},{passive:true});viewport.addEventListener('touchend',e=>{if(e.touches.length<2)zoomState.pinchStart=0;if(e.touches.length===0)zoomState.dragging=false})}
function touchDistance(a,b){return Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY)}
function openZoom(kind){const q=currentQuestion();if(!q)return;ensureZoomModal();let html='';if(kind==='visual'&&q.visual){html=q.visual;$('#zoomModalTitle').textContent='図を拡大';$('#zoomHint').textContent='ピンチで拡大縮小・1本指で移動できます'}else if(kind==='formula'&&q.formula){html=`<div class="formula formula-zoom">${q.formula.replace(/\n/g,'<br>')}</div>`;$('#zoomModalTitle').textContent='式・条件を拡大';$('#zoomHint').textContent='必要に応じて倍率を変更できます'}else return;$('#zoomPane').innerHTML=html;$('#zoomModal').classList.add('show');$('#zoomModal').setAttribute('aria-hidden','false');document.body.classList.add('modal-open');zoomReset()}
function closeZoom(){let m=$('#zoomModal');if(!m)return;m.classList.remove('show');m.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');zoomState.dragging=false}
function zoomIn(){zoomState.scale=clamp(zoomState.scale+.25,1,5);applyZoom()}function zoomOut(){zoomState.scale=clamp(zoomState.scale-.25,1,5);applyZoom()}function zoomReset(){zoomState.scale=1;zoomState.x=0;zoomState.y=0;applyZoom()}function applyZoom(){let pane=$('#zoomPane');if(!pane)return;pane.style.transform=`translate(${zoomState.x}px,${zoomState.y}px) scale(${zoomState.scale})`}
home();document.querySelector('nav button').classList.add('active');
